Traceback (most recent call last):
  File "/home/mfvargas/miniconda3/envs/gf0657-2024-ii/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/mfvargas/miniconda3/envs/gf0657-2024-ii/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mfvargas/miniconda3/envs/gf0657-2024-ii/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mfvargas/miniconda3/envs/gf0657-2024-ii/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/mfvargas/miniconda3/envs/gf0657-2024-ii/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/mfvargas/miniconda3/envs/gf0657-2024-ii/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/mfvargas/miniconda3/envs/gf0657-2024-ii/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import requests

# Solicitud GET
respuesta = requests.get('https://api.github.com/users/octocat')

# VerificaciÃ³n de la respuesta
if respuesta.status_code == 200:
    # La solicitud fue exitosa
    datos = respuesta.json()

    # Formateao de datos en formato JSON, para que sean mÃ¡s legibles
    json_formateado = json.dumps(datos, indent=4, ensure_ascii=False)
    # Despliegue del JSON formateado
    print(json_formateado)

    # Almacenamiento de datos JSON en un archivo
    with open('datos.json', 'w', encoding='utf-8') as archivo:
        json.dump(datos, archivo, indent=4, ensure_ascii=False)    
else:
    # Se produjo un error
    print(f"Error {respuesta.status_code}")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 12[0m
[1;32m      9[0m datos [38;5;241m=[39m respuesta[38;5;241m.[39mjson()
[1;32m     11[0m [38;5;66;03m# Formateao de datos en formato JSON, para que sean mÃ¡s legibles[39;00m
[0;32m---> 12[0m json_formateado [38;5;241m=[39m [43mjson[49m[38;5;241m.[39mdumps(datos, indent[38;5;241m=[39m[38;5;241m4[39m, ensure_ascii[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[1;32m     13[0m [38;5;66;03m# Despliegue del JSON formateado[39;00m
[1;32m     14[0m [38;5;28mprint[39m(json_formateado)

[0;31mNameError[0m: name 'json' is not defined

